services:
  nctsexcelupload:
    image: excel-image
    container_name: NctsExcelUpload
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      EXCHANGE_NAME: ${EXCHANGE_NAME}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      ROUTING_KEY: "Ncts Excel Upload/incomming"
      QUEUE_NAME: "ncts_excel_queue"
      PYTHONPATH: "/shared"
    networks:
      - csnetwork
    volumes:
      - "../scripts/Ncts Excel Upload:/app"
      - "../shared/classes.py:/shared/classes.py:ro"
      - "../shared/templates:/shared/templates:ro"
    command: ["/opt/venv/bin/python3", "main.py"]